* 青玉案 元夕
**** 东风夜放花千树, 更吹落, 星如雨. 宝马雕车香满路, 凤箫声动, 玉壶光转, 一夜鱼龙舞.
**** 蛾儿雪柳黄金缕, 笑语盈盈暗香去. 众里寻他千百度, 蓦然回首, 那人却在, 灯火阑珊处.

像东风吹散千树繁花一样，又吹得烟火纷纷，乱落如雨。
豪华的马车满路芳香。悠扬的凤箫声四处回荡，玉壶般的明月渐渐西斜，一夜鱼龙灯飞舞笑语喧哗。
美人头上都戴着亮丽的饰物，笑语盈盈地随人群走过，身上香气飘洒。
我在人群中寻找她千百回，猛然一回头，不经意间却在灯火零落之处发现了她。

* 长相思 山一程
**** 山一程, 水一程, 身向榆关那畔行, 夜深千帐灯.
**** 风一更, 雪一更, 聒碎乡心梦不成, 故园无此声.

走过一条条山路，走过一条条水路，正向榆关那边走去。夜深了，人们在帐篷里点灯。
晚上又刮风又下雪，声音嘈杂打碎了我思乡的梦，家乡没有这样的声音。

* 浣溪沙
**** 谁念西风独自凉, 萧萧黄叶闭疏窗, 沉思往事立残阳. 
**** 被酒莫惊春睡重, 赌书消的泼茶香, 当时只道是寻常.

秋风吹冷，孤独的情怀有谁惦念？
看片片黄叶飞舞遮掩了疏窗，伫立夕阳下，往事追忆茫茫。

酒后小睡，春日好景正长，闺中赌赛，衣襟满带茶香,
昔日平常往事，已不能如愿以偿。

* 永遇乐 京口北固亭怀古
**** 千古江山, 英雄无觅, 孙仲谋处
**** 舞榭歌台, 风流总被, 雨打风吹去
**** 斜阳草树, 寻常巷陌, 人道寄奴曾住
**** 想当年, 金戈铁马, 气吞万里如虎
**** 元嘉草草, 封狼居胥, 赢得仓皇北顾
**** 四十三年, 望中犹记, 烽火扬州路
**** 可堪回首, 佛狸祠下, 一片神鸦社鼓
**** 凭谁问: 廉颇老矣, 尚能饭否
* 木兰花令 拟古决绝词
**** 人生若只如初见, 何事秋风悲画扇.
**** 等闲变却故人心, 却道故人心易变.
**** 骊山语罢清宵半, 泪雨霖铃终不怨.
**** 何如薄幸锦衣郎, 比翼连枝当日愿.

与意中人相处应当总像刚刚相识的时候，是那样地甜蜜，那样地温馨，那样地深情和快乐。
但你我本应当相亲相爱，却为何成了今日的相离相弃？
如今轻易地变了心，你却反而说情人间就是容易变心的。
我与你就像唐明皇与杨玉环那样，在长生殿起过生死不相离的誓言，
却又最终作决绝之别，即使如此，也不生怨。
但你又怎比得上当年的唐明皇呢，他总还是与杨玉环有过比翼鸟、连理枝的誓愿。
