* 青玉案 元夕
** 东风夜放花千树, 更吹落, 星如雨. 宝马雕车香满路, 凤箫声动, 玉壶光转, 一夜鱼龙舞.
** 蛾儿雪柳黄金缕, 笑语盈盈暗香去. 众里寻他千百度, 蓦然回首, 那人却在, 灯火阑珊处.

像东风吹散千树繁花一样，又吹得烟火纷纷，乱落如雨。
豪华的马车满路芳香。悠扬的凤箫声四处回荡，玉壶般的明月渐渐西斜，一夜鱼龙灯飞舞笑语喧哗。
美人头上都戴着亮丽的饰物，笑语盈盈地随人群走过，身上香气飘洒。
我在人群中寻找她千百回，猛然一回头，不经意间却在灯火零落之处发现了她。

* 永遇乐 京口北固亭怀古
** 千古江山, 英雄无觅, 孙仲谋处
** 舞榭歌台, 风流总被, 雨打风吹去
** 斜阳草树, 寻常巷陌, 人道寄奴曾住
** 想当年, 金戈铁马, 气吞万里如虎
** 元嘉草草, 封狼居胥, 赢得仓皇北顾
** 四十三年, 望中犹记, 烽火扬州路
** 可堪回首, 佛狸祠下, 一片神鸦社鼓
** 凭谁问: 廉颇老矣, 尚能饭否

* 木兰花令 拟古决绝词
** 人生若只如初见, 何事秋风悲画扇.
** 等闲变却故人心, 却道故人心易变.
** 骊山语罢清宵半, 泪雨霖铃终不怨.
** 何如薄幸锦衣郎, 比翼连枝当日愿.

与意中人相处应当总像刚刚相识的时候，是那样地甜蜜，那样地温馨，那样地深情和快乐。
但你我本应当相亲相爱，却为何成了今日的相离相弃？
如今轻易地变了心，你却反而说情人间就是容易变心的。
我与你就像唐明皇与杨玉环那样，在长生殿起过生死不相离的誓言，
却又最终作决绝之别，即使如此，也不生怨。
但你又怎比得上当年的唐明皇呢，他总还是与杨玉环有过比翼鸟、连理枝的誓愿。

* 采桑子 明月多情应笑我
** 明月多情应笑我, 笑我如今, 孤负春心, 独自闲行独自鸣.
** 近来怕说当时事, 结编兰襟. 月浅灯深, 梦里云归何处寻?

多情的明月应嘲笑我的无情，嘲笑我辜负了她对我的柔情。
如今她已离我远去，我只能独自一人漫无目的地前行，独自一人悲伤地吟唱。
近来不敢提起当初的事情，那时我还和她情投意合、相亲相爱。
如今在惨淡的月光下。在暗淡的灯影里，远去的情人就像梦里悠悠飘去的一朵白云，无处追寻。
* 离思五首 其四
** 曾经沧海难为水, 除却巫山不是云.
** 取次花丛懒回顾, 半缘修道半缘君.

曾经到临过沧海，别处的水就不足为顾,
除了巫山，别处的云便不称其为云。
仓促地由花丛中走过，懒得回头顾盼,
这缘由，一半是因为修道人的清心寡欲，一半是因为曾经拥有过的你。
* 上邪
** 上邪(ye2), 我欲与君相知, 长命无绝衰(cui1).
** 山无陵(ling2), 江水为竭(jie2). 
** 冬雷震震, 夏雨(yu4)雪.
** 天地合, 乃敢与君绝.

上天呀！
我渴望与你相知相惜，长存此心永不褪减。
除非巍巍群山消逝不见，除非滔滔江水干涸枯竭,
除非凛凛寒冬雷声翻滚，除非炎炎酷暑白雪纷飞，
除非天地相交聚合连接，直到这样的事情全都发生时，我才敢将对你的情意抛弃决绝！


曾经沧海难为水, 除却巫山不是云
取次花丛懒回顾, 半缘修道半缘君 
MainEditorAssetTool.clickAssetTreeNodeToSetCurrentNode
* 江城子·乙卯正月二十日夜记梦
** 十年生死两茫茫, 不思量, 自难忘.
** 千里孤坟, 无处话凄凉.
** 纵使相逢应不识, 尘满面, 鬓如霜.
** 夜来幽梦忽还乡, 小轩窗, 正梳妆. 
** 相顾无言, 惟有泪千行.
** 料得年年肠断处, 明月夜, 短松冈.

两人一生一死，隔绝十年一起，相互思念却很茫然，无法相见。
不想让自己去思念，自己却难以忘怀。
妻子的孤坟远在千里，没有地方跟她诉说心中的凄凉悲伤。
即使相逢也应该不会认识，因为我四处奔波，灰尘满面，鬓发如霜。
晚上忽然在隐约的梦境中回到了家乡，只见妻子正在小窗前对镜梳妆。
两人互相望着，千言万语不知从何说起，只有相对无言泪落千行。
料想那明月照耀着、长着小松树的坟山，就是与妻子思念年年痛欲断肠的地方。
* 卜算子
** 我住长江头, 君住长江尾.
** 日日思君不见君, 共饮长江水.
** 此水几时休, 此恨何时已.
** 只愿君心似我心, 定不负相思意.

我居住在长江上游，你居住在长江尾底。
日日夜夜想你，却不能见你，你和我同饮一江绿水，两情相爱相知。
悠悠不尽的江水什么时候枯竭，别离的苦恨，什么时候消止。
只愿你的心，如我的心相守不移，就不会辜负了我一番痴恋情意。
* 花自飘零水自流
** 红藕香残玉簟(dian4)秋. 轻解罗裳(chang2), 独上兰舟. 
** 云中谁寄锦书来. 雁字回时, 月满西楼.
** 花自飘零水自流. 一种相思, 两处闲愁.
** 此情无计可消除. 才下眉头, 却上心头.

荷已残，香已消，冷滑如玉的竹席，透出深深的凉秋。
轻轻的脱下罗绸外裳，一个人独自躺上眠床。
仰头凝望远天，那白云舒卷处，谁会将锦书寄来？正是雁群一行行南归时候。
月光皎洁浸人，洒满这西边独倚的亭楼。
花，自顾地飘零，水，自顾地漂流。
一种离别的相思，牵动起两处的闲愁。
啊，无法排除的是——这相思，这离愁，刚从微蹙的眉间消失，又隐隐缠绕上了心头。
* 雨霖铃·寒蝉凄切 
** 寒蝉凄切，对长亭晚，骤雨初歇。都门帐饮无绪，留恋处，兰舟催发。
** 执手相看泪眼，竟无语凝噎。念去去、千里烟波，暮霭沉沉楚天阔。
** 多情自古伤离别，更那堪、冷落清秋节!今宵酒醒何处?杨柳岸、晓风残月。
** 此去经年，应是良辰好景虚设。便纵有千种风情，更与何人说！

秋后的蝉叫得是那样地凄凉而急促，面对着长亭，正是傍晚时分，一阵急雨刚停住。
在京都城外设帐饯别，却没有畅饮的心绪，正在依依不舍的时候，船上的人已催着出发。
握着手互相瞧着，满眼泪花，直到最后也无言相对，千言万语都噎在喉间说不出来。
想到这回去南方，这一程又一程，千里迢迢，一片烟波，那夜雾沉沉的楚地天空竟是一望无边。
自古以来多情的人最伤心的是离别，更何况又逢这萧瑟冷落的秋季，这离愁哪能经受得了！
谁知我今夜酒醒时身在何处？怕是只有杨柳岸边，面对凄厉的晨风和黎明的残月了。
这一去长年相别，相爱的人不在一起，我料想即使遇到好天气、好风景，也如同虚设。即使有满腹的情意，又能和谁一同欣赏呢？
* 南歌子词二首 / 新添声杨柳枝词
** 一尺深红胜曲尘，天生旧物不如新。
** 合欢桃核终堪恨，里许元来别有人。
** 井底点灯深烛伊，共郎长行莫围棋。
** 玲珑骰子安红豆，入骨相思知不知。

一袭深红色的长裙，日子久了便会蒙上了淡黄色的灰尘，自古以来旧东西就比不得新东西能讨人欢喜。
你我原本应该像合欢核桃一样坚贞不移，哪里想到你心里原来已经有了别人，让我对你终究有了恨意。
像井底下点蜡烛那样，深深地嘱咐你：虽然你要离开我远游，但我的心与你共长行，切记早归别违期。
手中玲珑骰子上的颗颗红点，都是最为相思的红豆；你知道不知道那深入骨中的就是我对你的相思意？

* 秋风词
** 秋风清，秋月明，
** 落叶聚还散，寒鸦栖复惊。
** 相思相见知何日？此时此夜难为情！
** 入我相思门，知我相思苦，
** 长相思兮长相忆，短相思兮无穷极，
** 早知如此绊人心，何如当初莫相识。

秋风凄清，秋月明朗。
风中的落叶时而聚集时而扬散，寒鸦本已栖息也被这声响惊起。
盼着你我能再相见，却不知在什么时候，此时此刻实在难耐心中的孤独悲伤，叫我情何以堪。
如果有人也这么思念过一个人，就知道这种相思之苦。
永远的相思永远的回忆，短暂的相思却也无止境，
早知相思如此的在心中牵绊，不如当初就不要相识。